AlgoritmO LEER3VALORES
	Definir NUM1 , NUM2 , NUM3,  MAYOR COMO ENTERO  
	
	ESCRIBIR "ESCRIBIR EL PRIMER NUMERO"
	Leer NUM1 
	ESCRIBIR " ESCRIBIR EL SEGUNDO NUMERO" 
	LEER NUM2 
	ESCRIBIR " ESCRIBIR EL TERCER NJUMERO"
	LEER  NUM3
	
	SI NUN1> NUM2 Y NUM1 > NUM3 ENTONCES MAYOR <-NUM1
	SiNo
		SI NUM2> NUM1 Y NUM2 > NUM3 ENTONCES MAYOR <-NUM2
		SINO 
			MAYOR <- NUM3
		FinSi
	FinSi
	ESCRIBIR " NUMERO MAYOR ES", MAYOR 
	
FinAlgoritmo
