AlgoritmO DIVISIONMAYOROIGUAL 
	DEFINIR A3 , B6 , NUMERO Como Real
	ESCRIBIR " ESCRIBIR PRIMER NUMERO " 
	LEER A3 
	Escribir BIBIR " ESCRIBIR SEGUNDO NUMERO"
	LEER B6 
	DIVISION <- A3 / B6
	SI A3 > B6 ENTONCES MAYOR <- A3 
	SINO 
		MAYOR <- B6
		ESCRIBIR " EL NUMERO MAYOR ES " MAYOR 
		SI A3 = B6 Entonces IGUAL <- A3 = B6 
			
		FinSi
	FinSi
	
	Escribir "EL RESIDUO ES" DIVISION
	
	
	
FinAlgoritmo
