AlgoritmO  MENORYSUMA
	DEFINIR A3 , B7 , C4 , MENOR Como Entero
	ESCRIBIR " ESCRIBIR PRIMER NUMERO" 
	LEER A3 
	ESCRIBIR " ESCRIBIR SEGUNDO NUMERO"
	LEER B7 
	ESCRIBIR " ESCRIBIR TERCER NUMERO"
	LEER C4
	SUMA <- A3 + B7 + C4 
	SI A3 < B7 Y A3 < C4 ENTONCES MENOR <-A3 
	SINO 
		SI B7 < A3 Y B7 < C4 ENTONCES MENOR <- B7 
		SINO 
			MENOR <- C4 
		FinSi
	FinSi
	ESCRIBIR " LAS SUMA DE LOS NUMEROS ES " SUMA 
	ESCRIBIR " EL NUMERO MENOR ES " MENOR 
	
	
FinAlgoritmo
