AlgoritmO VALORDEUNPRODUCTO
	DEFINIR VALORDELPRODUCTO , PORCENTAJEDELDESCUENTO , VALORFINAL , NUMERO Como Real
	ESCRIBIR" VALORDELPRODUCTO" 
	LEER VALORDELPRODUCTO
	PORCENTAJEDELDESCUENTO <- VALORDELPRODUCTO * 0.15
	VALORFINAL<- VALORDELPRODUCTO - PORCENTAJEDELDESCUENTO
	ESCRIBIR " VALORDELPRODUCTO : $ " VALORDELPRODUCTO 
	Escribir" PORCENTAJEDELDESCUENTO (15%) :$" PORCENTAJEDELDESCUENTO
	ESCRIBIR " VALORFINAL :$ " VALORFINAL
	
	
	
FinAlgoritmo
